@echo off
color 0a
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo !Coded by ChaosRekt [PRO CANCER]!
echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
echo -
echo -
echo Choissir la puissance de ralentissement
echo Minimum: 1 ( aucun effet )
echo Maximum: 65500 ( Gros effet )
echo Moyenne: 1024 ( Bon ralentissement ) !
echo Merci de choisir la puissance:
set/p packet=
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet%
start ping www.google.fr -t -l %packet% 