

@Echo off
color b
echo *** KeybindS_S Bat ***
echo Ce .bat reduit tes kb, il faut le lancer en administrateur
echo Il faut le relancer des que tu relances ton pc.
echo.
SET /P choix= Mon Kb (a) Ma Latency (b) A vous de decider ? (a/b)
REM Questionner L				
IF %choix%==a (	
REM Si la reponse est a ou e nous faisons deux commands differentes.																						
ECHO.
ECHO Execution en cours... 
ECHO.
ECHO 100%%
ipconfig /renew
ipconfig /flushdns
REM Arrive a la fin de la commande.
netsh interface tcp set global autotuning=normal
REM Ameliore la connexion de l'ordinateur
PAUSE
) ELSE (
ECHO.
ECHO Execution en cours...
ECHO.
ECHO 100%%
REM Arrive a la fin de la commande.
netsh interface tcp set global autotuning=restricted
REM Met la connexion en equilibre.
@PAUSE
)
netsh interface tcp show global
REM Afficher l'interface pour verifie que nous avons bien change de dispositif.
color a

ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
ECHO BY KEYBINDS_S
:CHATTE
ECHO. *******************************
ECHO. *********KeybindS_S************
ECHO. *******************************
@PAUSE
EXIT

